# // this should be placed in /var/lib/jenkins/workspace directory using sudo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: app
          image: ${IMAGE_NAME}
          ports:
            - containerPort: 8080
          env:
            - name: VAULT_ADDR
              value: "$VAULT_ADDR"
            - name: VAULT_TOKEN
              value: "$VAULT_TOKEN"
            - name: POSTGRES_USER
              value: "$POSTGRES_USER"
            - name: POSTGRES_PASSWORD
              value: "$POSTGRES_PASSWORD"
            - name: POSTGRES_DB
              value: "$POSTGRES_DB"
            - name: POSTGRES_HOST
              value: "$POSTGRES_HOST"
            - name: POSTGRES_PORT
              value: "$POSTGRES_PORT"