version: 2
updates:
  - package-ecosystem: "npm" # npm is used for Node.js projects
    directory: "/client" # Directory for the client-side package.json
    schedule:
      interval: "weekly" # You can adjust the interval if needed (e.g., daily, monthly)

  - package-ecosystem: "npm" # npm is used for Node.js projects
    directory: "/server" # Directory for the server-side package.json
    schedule:
      interval: "weekly" # Adjust the schedule as needed
